package com.example.pertemuan5mobile;


import java.util.ArrayList;

public class FoodData {
    public static String[][] data = new String[][]{
            {"Sup Krim Jagung", "Dari bahannya sendiri, sup krim jagung merupakan satu sajian vegetarian yang memiliki rasa oriental. Teksturnya kental, rasanya gurih, serta penuh nutrisi. Bisa dinikmati langsung tanpa makanan lainnya atau bisa juga menjadi pelengkap nasi atau roti. Hidangan ini bisa jadi pilihan Anda untuk sarapan atau saat cuaca dingin. \n \nSup krim jagung sangat cocok untuk menjaga kesehatan pencernaan. Selain itu bisa menambah selera atau nafsu makan bagi orang yang sedang dalam pemulihan kesehatan dan tidak ingin makan makanan yang bertekstur terlalu keras atau tebal.", "https://ds393qgzrxwzn.cloudfront.net/resize/m720x480/cat1/img/images/0/1fDYBzhfIb.jpg"},
            {"Vegan Waffle", "Waffle menggunakan telur dan susu dalam pembuatannya. Namun khusus untuk waffle vegetarian, penggunaan telur dihilangkan dan susunya diganti dengan susu kedelai atau susu almond. Tambahan topping aneka buah-buahan seperti stroberi atau madu pasti membuat perut keroncongan.", "https://ds393qgzrxwzn.cloudfront.net/resize/m720x480/cat1/img/images/0/jR9UwUTcZE.jpg"},
            {"Asinan Buah", "Makanan ini terbuat dari buah-buahan seperti kedondong, mangga muda, mentimun, jambu, dan sebagainya. Ada pula asinan sayur yang terdiri dari mentimun, tauge, kol, dan sawi asin. Asinan mengarah pada kudapan dengan rasa asam namun menyegarkan. Cocok dimakan sebagai camilan ketika bersantai. \n \n Asinan bisa langsung dinikmati, namun sebaiknya didinginkan dahulu di dalam kulkas. Cocok sekali dimakan saat cuaca panas.", "https://ds393qgzrxwzn.cloudfront.net/resize/m720x480/cat1/img/images/0/QEhh2scFke.jpg"},
            {"Tahu", "Tahu memiliki banyak manfaat, di antaranya sebagai sumber protein, zinc, zat besi, dan mengandung beberapa asam lemak omega-3 untuk menurunkan kolesterol.\nAnda juga bisa memilih varian tahu yang diperkaya kalsium. Makanan vegetarian ini mengandung sekitar 350 mg kalsium dan dapat memenuhi sekitar 30 persen dari kebutuhan vitamin D harian Anda.", "https://cdn1-production-images-kly.akamaized.net/BomF3WCGchra3TvEVmSuZbJAqWI=/640x640/smart/filters:quality(75):strip_icc():format(jpeg)/kly-media-production/medias/2825649/original/099511400_1560236129-iStock-523444303.jpg"},
            {"Lentil", "Lentil merupakan jenis kacang-kacangan yang kaya akan kandungan protein dan serat larut. Tidak hanya itu, makanan vegetarian ini memiliki kandungan zat besi, vitamin B, dan folat yang tinggi sehingga direkomendasikan untuk ibu hamil karena dapat mengurangi risiko bayi cacat lahir.\nBagi vegetarian pemula, konsumsi lentil direkomendasikan karena mengandung lebih sedikit gas sehingga tidak mengganggu pencernaan Anda.", "https://storage.googleapis.com/gen-atmedia/3/2012/08/1728c30a48fb9a076ff26e9366c4e5f452330204.jpeg"},
            {"Kacang-kacangan", "Kacang-kacangan kaya akan nutrisi, di antaranya zat besi, serat, magnesium, zinc, selenium, dan vitamin E. Studi terbaru menunjukkan meski kacang-kacangan tinggi kalori, tapi mengonsumsinya tidak menyebabkan kenaikan berat badan. Kacang-kacangan yang dimaksud di sini adalah kacang kenari, kacang tanah, almond, dan kacang mete.\n\nPenelitan dari Purdue University dan Loma Linda University juga menyatakan bahwa orang yang mengonsumsi kacang-kacangan dalam pola makannya cenderung memiliki berat badan lebih sedikit daripada mereka yang tidak. Kacang tanah bahkan bisa membantu menurunkan berat badan karena membuat Anda merasa kenyang lebih lama.", "https://www.nutriclub.co.id/_default_upload_bucket/image-thumb__1860__default/6-manfaat-kacang-kacangan-untuk-ibu-dan-janin.webp"},
            {"Biji-bijian", "Beberapa biji-bijian diperkaya dengan vitamin B-12 yang sulit didapatkan pada makanan lainnya. Selain itu, biji-bijian umumnya kaya akan zat besi, kalsium, dan serat yang tidak larut dalam air.\n\nMakanan vegetarian jenis biji-bijian, seperti gandum utuh dan beras merah, tidak hanya membantu menurunkan kadar kolesterol dalam tubuh Anda, tetapi juga dapat mengurangi risiko kanker usus besar dan gangguan pencernaan lainnya.", "https://media.tabloidbintang.com/files/thumb/kacang-kacangan_depositphotos_21191267_l-20151.jpg/745"},
            {"Sayuran hijau", "renyah teksturnya. Plecing kangkung bisa dijadikan sebagai makanan pendamping nasi atau langPada dasarnya semua sayuran itu menyehatkan. Akan tetapi, sayuran hijau seperti bayam, brokoli, dan kale mengandung kadar zat besi yang lebih tinggi ketimbang sayuran lainnya. Bayam bahkan yang mengandung sekitar 6 gram zat besi atau sekitar sepertiga dari kebutuhan sehari-hari.\n\nSayuran hijau juga merupakan sumber antioksidan penangkal kanker, kaya akan asam folat dan vitamin A, serta mengandung kalsium. Anda bisa mengonsumsi sayuran hijau ini dalam bentuk salad dengan menambahkan sedikit perasan lemon.", "https://storage.trubus.id/storage/posts/t20181012/big_ecfd43d185fdc8015cf0d8141d863d50670758ec.jpg"},
            {"Rumput laut", "Selain menjadi sumber zat besi dan fitokimia, jenis-jenis rumput laut, seperti alaria, dulse, kelp, nori, spirulina, juga merupakan sumber mineral yang diperlukan oleh tubuh.\n\nKandungan beragam mineral yang ada dalam rumput laut meliputi magnesium, kalsium, yodium, besi, dan kromium. Tidak hanya itu, rumput laut juga mengandung vitamin A, C, dan E. Selain mudah ditemukan di pasaran, rumput laut jenis nori dan spirulina juga mudah untuk diolah menjadi makanan vegetarian.", "https://image-cdn.medkomtek.com/Vl6jRyEHzq7pty1fRR3jirigp6s=/0x45:848x523/1200x675/klikdokter-media-buckets/medias/2302007/original/068762500_1543906773-Konsumsi-Rumput-Laut-untuk-Tubuh-Lebih-Sehat-By-YASUHIRO_AMANO-123rf.jpg"},
            {"Buah kering", "Buah kering juga termasuk makanan vegetarian yang direkomendasikan untuk pemula. Buah-buahan kering ini dapat berupa aprikot, kismis, plum, mangga, nanas, ara, kurma, ceri, dan cranberry. Buah-buahan tersebut menyediakan beragam mineral, vitamin, dan serat sebagai nutrisi seimbang bagi tubuh.\n\nAda banyak opsi dalam penyajian buah kering, di antaranya dapat Anda jadikan sebagai camilan sehat, membuatnya menjadi salad, dan juga disajikan bersamaan dengan puding, kue, atau sereal.", "https://cdn.idntimes.com/content-images/post/20180423/alacarte-jiyugaoka-ed56461ae70c22f46acb1c61f91333b9_600x400.jpg"},
    };
    public static ArrayList<Food> getListData(){
        ArrayList<Food> list = new ArrayList<>();
        for (String[] aData : data) {
            Food food = new Food();
            food.setName(aData[0]);
            food.setDesc(aData[1]);
            food.setPhoto(aData[2]);
            list.add(food);
        }
        return list;
    }
}



